### ISSUE TITLE
Docs: Embedding Tileset in Map

### ISSUE THREAD

**Issue by elFabo01** [SSBMTonberry/tileson#29]
I have been unsuccessful parsing until i embedded the tilesets in the map json. It would help if that would have been mentioned in the docs. I only got the idea that this was the issue when searching through your test cases.
Keep up the good work!

**Comment by SSBMTonberry** [comment]
Thanks for mentioning! I'll add a note on this in the README :slightly_smiling_face: 
Actually, everything related to the map must be embedded for Tileson to be able to resolve it. External files referenced in a map are not parsed.

**Comment by FinnG** [comment]
Are there any plans to add support for external tilesets?

**Comment by SSBMTonberry** [comment]
@FinnG : I've been on the fence of supporting external Tilesets mostly because it will require dependencies to external files, and having things embedded make everything more convenient and faster to resolve. I see the argument if you were to use the same tileset on several maps (let's say 10), and the tileset contains a lot of information, but if you want small map-files, the latest version of Tileson supports LZMA compression (see release notes for 1.3.0 alpha), which can make maps ~30 times smaller, and doesn't take much more time to read. 

There haven't really been many people requesting this feature, but if it honestly is something you really need/want, I'll consider adding it on the current roammap, but if not: I'd rather wait and see if there are other people requesting this. I don't like the idea of having to resolve everything by having to load a lot of external files. Tilesets are not the only thing that can be external, either, so if I were to support external Tilesets, where do I draw the line? :stuck_out_tongue:

**Comment by FinnG** [comment]
Thanks for the quick response.

I'm not desperate for this feature, it would be more of a nice to have.
