### ISSUE TITLE
Tile-IDs in animations are inconsistent with the other Tileson IDs

### ISSUE THREAD

**Issue by SSBMTonberry** [SSBMTonberry/tileson#41]
Tileson uses an ID mapping making sure the IDs are aways consistent, while Tiled sometimes got a diff in the IDs of a tile definition and a tile used in a tileset. Somehow the tile IDs for animations have never been handled correctly, and is thus inconsistent with the other IDs, which shows when attempting to map one of these IDs to a tile of a tileset.

**Comment by SSBMTonberry** [comment]
This is now fixed. A workaround in the past would be to just increment the tile ID by 1, which means thaat this is a potential breaking change for anyone that have used animations in the past.

**Comment by EmVee381** [comment]
hi  i reached same issue... i have two tilesets in one map now... first contains 840 tiles, second contains 12, lets continue with second tileset, this second tileset is not used in any layer of map, i have defined animation only on first tile. so. first layer with first tileset is ok as it has correct ids, but second one is filled by fuction generateMissingTiles. 

if i investigated ids generated in second tilesets i see it begin with 1 which i s tile with animation... then it continue with ids generated by generateMissingTiles but it uses "gId" not "id" so second tile in second tileset is 841, third is 842... so animatiot cant work because tileset now contains wrong ids...

is it clear what i mean? i dont understand why it uses gId if it is related to tileset, not map.

thank you.... i will continue to find workaround for my issue... but i will be happy if you clarify me sense or confirm its kind of bug, or just lead me right way... thx
